// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5pj6Nmve3uOJ19y2nwUrcCFTzj7DV1Y',
    appId: '1:670620250477:web:ae1ad50eca170e8182ea64',
    messagingSenderId: '670620250477',
    projectId: 'tuni-c59cd',
    authDomain: 'tuni-c59cd.firebaseapp.com',
    storageBucket: 'tuni-c59cd.firebasestorage.app',
    measurementId: 'G-HHYJC34T0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnP9wuU0W19acNsq5O7I5HZiPgs0csuIU',
    appId: '1:670620250477:android:1c6507d5cab7327682ea64',
    messagingSenderId: '670620250477',
    projectId: 'tuni-c59cd',
    storageBucket: 'tuni-c59cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjg2WjHJDSfmC3a_bfTY9a8pevJATT8Gg',
    appId: '1:670620250477:ios:a588b29859f8cce282ea64',
    messagingSenderId: '670620250477',
    projectId: 'tuni-c59cd',
    storageBucket: 'tuni-c59cd.firebasestorage.app',
    iosBundleId: 'com.example.tunifith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjg2WjHJDSfmC3a_bfTY9a8pevJATT8Gg',
    appId: '1:670620250477:ios:a588b29859f8cce282ea64',
    messagingSenderId: '670620250477',
    projectId: 'tuni-c59cd',
    storageBucket: 'tuni-c59cd.firebasestorage.app',
    iosBundleId: 'com.example.tunifith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo5pj6Nmve3uOJ19y2nwUrcCFTzj7DV1Y',
    appId: '1:670620250477:web:ddb6a1d92f18ddb582ea64',
    messagingSenderId: '670620250477',
    projectId: 'tuni-c59cd',
    authDomain: 'tuni-c59cd.firebaseapp.com',
    storageBucket: 'tuni-c59cd.firebasestorage.app',
    measurementId: 'G-29WBCL73VB',
  );
}
